[project]
name = "application"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aws-lambda-powertools>=3.31.1",
    "boto3>=1.43.56",
    "botocore[crt]>=1.43.56",
    "pillow>=12.3.0",
    "pydantic>=2.13.4",
    "python-ulid>=4.0.1",
]
license = { text = "MIT" }

[dependency-groups]
dev = [
    "black>=26.5.1",
    "codespell>=2.4.3",
    "isort>=8.0.1",
    "mypy>=2.3.0",
    "pytest>=9.1.1",
    "ruff>=0.16.0",
    "taskipy>=1.14.1",
    "types-boto3-custom",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.taskipy.tasks]
typecheck = "mypy -p src --strict"
format = "ruff check . --fix && ruff format . && ruff check . --select I --fix && black . --target-version py314"
test = "pytest"
codespell = "codespell"
check = "uv run task format && uv run task typecheck && uv run task test && uv run task codespell"

# Run with uv run task format, uv run task test etc

[tool.isort]
profile = "black"

[tool.black]
line-length = 88

[tool.uv.sources]
types-boto3-custom = { path = "vendored/types_boto3_custom-1.43.56-py3-none-any.whl" }
